#!/usr/bin/env python3
"""ChimeraX figures for the tail_collar_fiber WT/evolved HOMOTRIMER -- built
after discovering (src/tcf_interface_contacts.py) that all 3 ROI positions
(444, 464, 465) sit at direct inter-chain contact (2.85-3.28 A) in both
variants. The earlier monomer-based figures (roi_structure_figures_hp3.py)
can't show this at all -- a single chain has no interface to see.

Two figures:

1. Trimer overlay -- WT (blue) and evolved (orange) trimers superimposed
   (ChimeraX matchmaker aligned on chain A only, which carries the whole
   6-chain overlay since AF3 doesn't guarantee A/B/C are assigned the same
   way between the two independent folding runs), ROI residues shown as
   spheres on all 3 chains of each variant.
   -> analysis/figures/roi_structures_hp3/tcf_trimer_overlay.png

2. Interface close-ups (one per variant) -- chain A's 3 ROI residues as red
   ball-and-stick, its two neighboring chains as thin grey sticks/transparent
   cartoon, so the actual inter-chain contact is visible directly (not just
   asserted from the distance table).
   -> analysis/figures/roi_structures_hp3/tcf_interface_{wt,evolved}.png

Usage:
    python src/tcf_trimer_figures.py
    python src/tcf_trimer_figures.py --no-render
    python src/tcf_trimer_figures.py --chimerax /path/to/ChimeraX
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
STRUCT_DIR = REPO / "data" / "structures"
STRUCT_MAP_PATH = STRUCT_DIR / "hp3_structure_map.json"
OUT_DIR = REPO / "analysis" / "figures" / "roi_structures_hp3"

DEFAULT_CHIMERAX_CANDIDATES = [
    r"C:\Program Files\ChimeraX 1.10\bin\ChimeraX.exe",
    r"C:\Program Files\ChimeraX 1.9\bin\ChimeraX.exe",
    "/Applications/ChimeraX-1.11.1.app/Contents/MacOS/ChimeraX",
]

VARIANT_COLOR = {"wt": "#2a78d6", "evolved": "#eda100"}
CHAINS = ["A", "B", "C"]
ROI_POSITIONS = [444, 464, 465]
ROI_RESIDUE = {"wt": {444: "Y", 464: "K", 465: "Y"},
               "evolved": {444: "H", 464: "R", 465: "H"}}
# from src/tcf_interface_contacts.py: chain A's nearest neighbor, per variant.
NEAREST_TO_A = {"wt": {444: "B", 464: "C", 465: "C"},
                "evolved": {444: "C", 464: "C", 465: "B"}}


def _find_chimerax() -> str | None:
    for c in DEFAULT_CHIMERAX_CANDIDATES:
        if Path(c).exists():
            return c
    return None


def build_overlay_cxc() -> tuple[str, Path]:
    smap = json.loads(STRUCT_MAP_PATH.read_text())
    wt_path = STRUCT_DIR / smap["tcf_3mer_wt"]["cif"]
    ev_path = STRUCT_DIR / smap["tcf_3mer_evolved"]["cif"]
    out = OUT_DIR / "tcf_trimer_overlay.png"

    lines = [
        "# Auto-generated by src/tcf_trimer_figures.py -- tail_collar_fiber trimer overlay.",
        "set bgColor white", "lighting soft", "graphics silhouettes true",
        f"open {wt_path}",   # model #1 = wt (chains A,B,C)
        f"open {ev_path}",   # model #2 = evolved (chains A,B,C)
        "hide #1,2 atoms", "cartoon #1,2",
        "mm #2/A to #1/A",   # align on chain A only; carries the whole evolved trimer
        "color #1 #2a78d6", "color #2 #eda100",
        "transparency #1,2 60 cartoons",
        "",
    ]
    for model_n, variant in ((1, "wt"), (2, "evolved")):
        color = VARIANT_COLOR[variant]
        for chain in CHAINS:
            for pos in ROI_POSITIONS:
                S = f"#{model_n}/{chain}:{pos}"
                lines += [f"show {S} atoms", f"style {S} sphere", f"color {S} {color}"]
    lines += ["view pad 0.3", ""]  # extra margin: the trimer overlay is taller than the monomer

    legend = [
        f"WT ({VARIANT_COLOR['wt']}): Y444, K464, Y465 -- all 3 chains",
        f"evolved ({VARIANT_COLOR['evolved']}): H444, R464, H465 -- all 3 chains",
        "all 3 positions sit at direct inter-chain contact (2.85-3.28 A) in both variants",
    ]
    for i, (txt, color) in enumerate(zip(legend, (VARIANT_COLOR["wt"], VARIANT_COLOR["evolved"], "black"))):
        lines.append(
            f'2dlabels create legend_{i} text "{txt}" xpos 0.02 ypos {0.80 - 0.06 * i} '
            f'size 16 color {color}'
        )
    lines += [f"save {out} width 1600 height 1200 supersample 3", ""]
    return "\n".join(lines), out


def build_interface_cxc(variant: str) -> tuple[str, Path]:
    smap = json.loads(STRUCT_MAP_PATH.read_text())
    cif_path = STRUCT_DIR / smap[f"tcf_3mer_{variant}"]["cif"]
    out = OUT_DIR / f"tcf_interface_{variant}.png"

    lines = [
        f"# Auto-generated by src/tcf_trimer_figures.py -- tail_collar_fiber {variant} interface close-up.",
        "set bgColor white", "lighting soft", "graphics silhouettes true",
        f"open {cif_path}",
        "hide #1 atoms", "cartoon #1", "color #1 #bfbfbf", "transparency #1 55 cartoons",
        "",
    ]
    # No in-scene 3D text labels: the 3 ROI positions sit close enough in this
    # zoomed view that per-residue labels collide (as the earlier version of
    # this figure showed). A fixed 2D legend below identifies each instead.
    legend_lines = []
    for pos in ROI_POSITIONS:
        S = f"#1/A:{pos}"
        nb = NEAREST_TO_A[variant][pos]
        env = f"({S} :<6 & #1/{nb})"
        code = f"{ROI_RESIDUE[variant][pos]}{pos}"
        lines += [
            f"show {S} atoms", f"style {S} ball", f"size {S} stickRadius 0.3",
            f"color {S} byhetero", f"color {S} & C #d62728",
            f"show {env} & sidechain atoms", f"style {env} stick", f"size {env} stickRadius 0.12",
            f"color {env} & C #9a9a9a",
        ]
        legend_lines.append(f"{code} (chain A -> {nb})")
    lines += ["view #1/A:444,464,465 pad 0.4", ""]
    for i, txt in enumerate(legend_lines):
        lines.append(
            f'2dlabels create legend_{i} text "{txt}" xpos 0.02 ypos {0.80 - 0.06 * i} '
            f'size 16 color #d62728'
        )
    lines += [
        f"save {out} width 1600 height 1200 supersample 3",
        "",
    ]
    return "\n".join(lines), out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--chimerax", default=None)
    ap.add_argument("--no-render", action="store_true")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cxc_paths = []

    cxc, out = build_overlay_cxc()
    p = OUT_DIR / "render_tcf_trimer_overlay.cxc"
    p.write_text(cxc)
    cxc_paths.append(p)
    print(f"wrote {p.relative_to(REPO)} -> {out.relative_to(REPO)}")

    for variant in ("wt", "evolved"):
        cxc, out = build_interface_cxc(variant)
        p = OUT_DIR / f"render_tcf_interface_{variant}.cxc"
        p.write_text(cxc)
        cxc_paths.append(p)
        print(f"wrote {p.relative_to(REPO)} -> {out.relative_to(REPO)}")

    if args.no_render:
        print("--no-render: skipping ChimeraX.")
        return

    chimerax = args.chimerax or _find_chimerax()
    if not chimerax or not Path(chimerax).exists():
        sys.exit("ChimeraX not found; pass --chimerax PATH")

    for p in cxc_paths:
        print(f"Rendering {p.name}...")
        subprocess.run([chimerax, str(p)], check=True)
    print("Done.")


if __name__ == "__main__":
    main()
